#!/bin/bash
#map DMRs to predifined genomic regions (gencode annotation files)
#PATH of genome annotation files that generated by s1_run_annotation.sh ( 
in_GENE_REGION='../../data/fl_mr/in_data/in_genome_regions/'
in_sorted_refFlat='gencode.v19.annotation_gene.ref_clean_sorted.bed'
logProb_cutoff=0.7

#PATH of DMRs predicted by dmr_analysis
in_mr_result_folder='../../data/fl_mr/in_data/DMR_CpG_context'
mr_IN_FILE='2_chroms_all_mr_data_range_dmrRanking'

#OUTPUT PATH
out_result_folder='../../data/fl_mr/out_data/'
out_folder4genome_map='out_map2genome'
out_file4genome_map=gcb_vs_tumor_DMR_hyper_hypo_mix_${logProb_cutoff}.csv

#START RUN
#a) map DMR to predefined genomic regions such as TSS, TES, gene et al.
dmr_analysis dmr_map2genome --in_sortedDMR_file ${in_mr_result_folder}/${mr_IN_FILE}.bed \
	--in_geneRegion_file ${in_GENE_REGION}/list_region_files.txt_gencode \
	--in_outFile_folder ${out_result_folder}/${out_folder4genome_map} \
	--in_refFlat_file ${in_GENE_REGION}/data/${in_sorted_refFlat}
echo dmr_map2genome - Done
 
#b) calculate percentage of DMR in annotated genomic regions
dmr_analysis dmr_cal2genome_percent --in_outFile_folder ${out_result_folder}/${out_folder4genome_map} \
        --in_outFile_name ${out_file4genome_map} --in_LogReg_proba ${logProb_cutoff} \
        --in_fileName_string $mr_IN_FILE  
echo dmr_cal2genome_percent - Done

#c) plot percentage of DMR in annotated genomic regions
dmr_analysis dmr_percent2plot --in_countFile_folder ${out_result_folder}/${out_folder4genome_map} \
        --in_countFile_name ${out_file4genome_map}
echo dmr_percent2plot - Done


