#!/bin/bash
#SBATCH --job-name=demo2-dds
#SBATCH --account=nn4605k
#SBATCH --time=15:00:00
#SBATCH --mem-per-cpu=15G --partition=bigmem 
# Number of cores:
#SBATCH --cpus-per-task=20

#set up job enviroment
#source /etc/profile.d/modules.csh
#source /cluster/bin/jobsetup
#module use --append /cluster/etc/modulefiles
#module load java/jdk1.7.0_80
#module unload Java/1.8.0_212
#module purge
#module --ignore-cache load Java/1.7.0_80

#the last examples is for dds_analysis after preprocessing data in part1 , part2
./run_hap1_cell_part1.sh
./run_hap1_cell_part2.sh
./run_hap1_cell_part3.sh

