#!/bin/bash
#This script is used to provide a demo for perfroming 
#	dds_analysis dTarget_methy_vs_express
#	on rat data by integrating DMR and DEG data together
#	and predicting putative target genes to a DMR based on their 
#	associations from either TSS or 5'distance reginos.

#main path of data
IN_DATA_PATH='../../data/rat_data/in_data/final_demo_data/rat_data/'
#path of DMR results of dmr_analysis
IN_MR_PATH=${IN_DATA_PATH}'/out_data/DMR_CpG_context/'
#path of DEG results of bpb3
IN_DEG_PATH=${IN_DATA_PATH}'/in_data/DEG/'

#path to output data
OUT_PATH='../../data/rat_data/out_data/'

#path to exported MRs that are not located in TSS or enhancer regions
FILE_FOLD=${OUT_PATH}/out4mr_not_in_tss_enhancer
#file name for background sample list that contain all MRs not located in TSS or enhancers
BACK_FILE=${OUT_PATH}/background_samples_list.tsv

is_run_dmr_export=1 # 1 for exporting, other values for skipping this step 
is_run_dtarget=1    # 1 for run dTarget prediction , other values for skipping this step

if [ $is_run_dmr_export == 1 ];
then
##15 here two input file are generated by preprocess_data4dds_test.py 
#1. export data for dmr regions that located in either TSS or 5distance regions
dmr_analysis dmr_exportData \
        --input_mr_data_folder ${IN_MR_PATH} \
        --output_file_folder ${OUT_PATH}/out4dmr_in_deg_tss_5dist \
        --input_file_format 0 \
        --number_of_processes 10 --input_file ${OUT_PATH}/uqdmr_regions_in_deg_tss_5dist_rat.bed -wtStr '_Ctrl'
echo "Export data of DMRs overlapping to TSS or 5distnace - Done "
echo ""

#2. export data for mrs that are not in tss and enhancer 
dmr_analysis dmr_exportData  \
        --input_mr_data_folder ${IN_MR_PATH} \
        --output_file_folder ${OUT_PATH}/out4mr_not_in_tss_enhancer \
        --input_file_format 0 \
        --number_of_processes 10 --input_file ${OUT_PATH}/mr_regions_not_in_enhancers_tss.bed -wtStr '_Ctrl'
echo "Export data of MRs not in TSS or enhancers - Done "
echo ""
fi
#end export data

#16. 
#3. create background file list if it is not exist.
#for large list of files, bash script may not work but a python script is needed!
if ! [ -f $BACK_FILE ];
then
  echo $BACK_FILE " not exists and create one ! "
  if [ -e $FILE_FOLD ];
  then
    	ls  ./${FILE_FOLD}/chr*/data/*raw*.* > $BACK_FILE
        echo "Create " $BACK_FILE 
  else
    	echo "Cannot create background file because no data folder find! " $FILE_FOLD
  fi
fi

#17. 
#4. to run dds_analysis dTarget_methy_vs_express for predicting putative target genes to DMRs
# unique gene to DMR file prepared by  preprocess_data4dds_test.py
gene_mr_file=${OUT_PATH}/uqGeneDmr_regions_in_deg_tss_rat.bed

# tab delimited DEG file prepared by preprocess_data4dds_test.py
gene_exp_file=${IN_DEG_PATH}'/Adrenal1vsAdrenal2_DEG_genes_zscores.tsv'

# path of DMRs associated with DEG, TSS and 5distance, prepared by step 1.
in_mr_data_folder=${OUT_PATH}/out4dmr_in_deg_tss_5dist
# a file for a list of background samples
in_background_mr_file=$BACK_FILE
#number of random sampling
number_of_samples=10


if [ $is_run_dtarget == 1 ];
then
#18. 
#5. to test target gene and DMRs assocation from TSS regions
dds_analysis dTarget_methy_vs_express -inGeneMRfile $gene_mr_file  -mrTAB  \
	-inGeneEXPfile $gene_exp_file -expTAB \
	-inMRfolder $in_mr_data_folder -outName 'tss_region_' \
	-output_path $OUT_PATH -sampleName 'sample_name4replace.tsv' \
	-pathDepth 1 -inBackgroundList $in_background_mr_file -cutoff 0.05 -totalSamples $number_of_samples -numOfprocesses 10

echo "Done with TSS target gene prediction"
echo ""

#19. 
#6. to test target gene and DMRs associatioin from  5dist regions
gene_mr_file=${OUT_PATH}/uqGeneDmr_regions_in_deg_5dist_rat_overlap_enhancer.bed
dds_analysis dTarget_methy_vs_express -inGeneMRfile $gene_mr_file -mrTAB  \
	-inGeneEXPfile $gene_exp_file -expTAB \
	-inMRfolder $in_mr_data_folder -outName 'distance_region_'  \
	 -output_path $OUT_PATH -sampleName 'sample_name4replace.tsv' \
	-pathDepth 1 -inBackgroundList $in_background_mr_file -cutoff 0.01 -totalSamples $number_of_samples -numOfprocesses 10

echo "Done with 5distance target gene prediction"
echo ""

fi
#end dTarget run

#20. 
#7. plot selected target gene and DMR associatoins
echo ${gene_exp_file}
echo  ${OUT_PATH}/out4dmr_in_deg_tss_5dist 
echo ${OUT_PATH}

dds_analysis plot_mr_vs_exp -inGeneEXPfile ${gene_exp_file}  \
        -dpi 300 -inMRfolder ${OUT_PATH}/out4dmr_in_deg_tss_5dist \
	-sampleName sample_name4replace.tsv -expTAB -inGene 'Tab2' -inMR 'chr1:mr16' -wtStr '_Ctrl' -output_path ${OUT_PATH}

